# # run `npm run github-publish` to publish a release for the master branch
# # this will create a release with the latest changes from master
# # and publish it to github
# # this will also create a tag for the release

# name: Create Release for Master

# on:
#   push:
#     branches:
#       - master
      
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#   # use nodejs 18
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '18'
#           cache: 'npm'
#   # checkout the repo
#       - uses: actions/checkout@v2
#   # install dependencies
#       - run: npm ci
#   # build the project
#       - run: npm run make
#   # create tag name from package.json and output it